[project]
name = "infinity-utils"
version = "0.1.2"
description = "A collection of utility functions and classes."
authors = [
      {name = "Infinity AI Lab"}
  ]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic",
    "google-cloud-firestore",
]
